apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: text-generator
spec:
  containers:
  - name: my-container
    image: rthatikonda/text-generator-app:latest
    ports:
    - containerPort: 5000
